CREATE TABLE Contacts (
  id INT PRIMARY KEY IDENTITY(1,1),
  firstname NVARCHAR(255) NOT NULL,
  lastname NVARCHAR(255) NOT NULL,
  country NVARCHAR(255) NOT NULL,
  city NVARCHAR(255) NOT NULL,
  street NVARCHAR(255) NOT NULL,
  zipcode INT NOT NULL,
  phone NVARCHAR(255) NOT NULL,
  email NVARCHAR(255) NOT NULL UNIQUE
);